### ISSUE TITLE
boost missing in platform or host

### ISSUE THREAD

**Issue by KarstenHopp** [fedora-modularity/baseruntime-package-lists#43]
boost is required by a huge number of packages and should probably be in platform.
This will also fix the mongodb issue with the missing libboost_chrono:
https://bugzilla.redhat.com/show_bug.cgi?id=1509934

**Comment by sgallagher** [comment]
I don’t think Boost belongs in platform at all. I think that it is a utility library that would benefit greatly by having its own module with streams for each major version (which are ABI-incompatible and must be recompiled against).

**Comment by igor-raits** [comment]
totally support @sgallagher here, boost is breaking every version and it doesn't make sense to support it in platform.

**Comment by KarstenHopp** [comment]
I agree, looking at boost's history they tend to break ABI with every major update.
I'll close this, thanks for your feedback !
