### ISSUE TITLE
Please add bison/yacc/flex/m4 to platform

### ISSUE THREAD

**Issue by KarstenHopp** [fedora-modularity/baseruntime-package-lists#44]
These are developer tools that we need to provide so that users can build their own packages.
At least bison is also a runtime dependency for some packages.

**Comment by contyk** [comment]
@KarstenHopp, please file these here: https://github.com/fedora-modularity/hp

`yacc`, `flex` and `m4` are already in Platform -- these are explicitly included in the minimal RPM buildroot. `bison` is missing, however.

**Comment by contyk** [comment]
I would say `bison` should be part of `platform`. I've checked all its binary packages and their dependencies and it wouldn't pull anything else in. Over 300 Fedora packages buildrequire it explicitly, with probably many more just not declaring the dependency.

@sgallagher, opinions?

**Comment by igor-raits** [comment]
+1 from me given @contyk insight about yacc/flex/m4
